import type { DeedTemplate } from "./deed-templates";

/**
 * Nine affidavits the office supplied, held verbatim.
 *
 * Seven arrived executed — names, PAN and Aadhaar numbers, addresses, survey
 * and document registration numbers, a school and a university. Two arrived
 * already unfilled. Everything identifying is a {{token}} the form fills or a
 * blank rule the counter completes; the party frame each one opens with is
 * tokenised so the name, the parent's name and the address come from the form.
 */

export type AffidavitTemplateId =
  | "affidavit-separate-property"
  | "affidavit-no-claim-land"
  | "affidavit-no-proceedings"
  | "affidavit-gst-records"
  | "affidavit-minor-travel-consent"
  | "affidavit-lost-land-document"
  | "affidavit-sponsorship"
  | "affidavit-gas-name-change"
  | "affidavit-non-criminal-gap"
  ;

export const AFFIDAVIT_TEMPLATES: Record<AffidavitTemplateId, DeedTemplate> = {
  "affidavit-separate-property": {
    id: "affidavit-separate-property",
    baseType: "deed",
    name: "Affidavit — Property Held Independently",
    deedTitle: "AFFIDAVIT",
    roleA: "DEPONENT",
    roleB: "",
    description: "A spouse declares that a property is theirs alone and not liable for the other's dues.",
    body: [
      { text: "AFFIDAVIT", heading: true },
      { text: "I, {{nameA}}, holding Permanent Account Number (PAN): __________________________ Wife of {{parentA}}, aged ___ years, residing at {{addressA}} , do hereby solemnly affirm and state as follows:" },
      { text: "1. That I am the deponent herein and I am well acquainted with the facts stated below and competent to swear this affidavit." },
      { text: "2. That my husband, Mr. __________________________ B, holding Permanent Account Number (PAN): __________________________ has certain pending income tax liabilities with the Income Tax __________________________" },
      { text: "3. That I hereby state that I am not liable for any of the aforesaid dues or liabilities of my husband in my personal capacity as per the provisions of the income Tax Act, __________________________ particulary sections 222 and 281, recovery proceedings can be initiated only aganist the assets of the assessee, and any property independently owned by a third party, in which the assessee has no right, title, or interest, cannot be subjected to attachment." },
      { text: "4. That I further state that the immovable property bearing details as follows: Individual House at Chennai(hereinafter referred to as the “said property”) is my absolute and self-acquired property." },
      { text: "5. That the said property was given to me by my parents, namely Mr. __________________________ T K and Mrs. __________________________ R, out of their own independent sources of income, through a valid gift, and without any financial contribution, direct or indirect, from my husband." },
      { text: "6. That my husband has no right, title, interest, claim, or share whatsoever in the said property at any time." },
      { text: "7. That I submit that the said property does not form part of my husband’s assets and cannot be considered for attachment or recovery proceedings in respect of his tax liabilities." },
      { text: "8.That any attempt to attach or proceed against my property for recovery of my husband’s dues would be unjustified and contrary to law." },
      { text: "9. That this affidavit is made to declare and confirm that my property is independent and separate from my husband’s financial obligations." },
      { text: "DEPONENT(Signature)Place: __________________________ : {{executionDate}}" },
      { text: "__________________________ the above-named deponent, do hereby verify that the contents of paragraphs 1 to 9 are true and correct to the best of my knowledge and belief and that nothing material has been concealed therefrom." },
      { text: "__________________________ at Chennai on this 22 day of __________________________" },
      { text: "DEPONENT", heading: true },
      { text: "Witness 1Witness 2" },
    ],
  },
  "affidavit-no-claim-land": {
    id: "affidavit-no-claim-land",
    baseType: "deed",
    name: "Affidavit — No Claim to Land",
    deedTitle: "AFFIDAVIT",
    roleA: "DEPONENTS",
    roleB: "",
    description: "Relatives disclaim any right, title or interest in a scheduled property. Carries a schedule.",
    body: [
      { text: "AFFIDAVIT", heading: true },
      { text: "We, {{nameA}}, S/o. {{parentA}}, __________________________ S/o. __________________________ all residing at {{addressA}} , do hereby solemnly affirm and sincerely state as follows," },
      { text: "We state that we came to knowledge that one __________________________ S/o. {{parentA}}, residing at {{addressA}}" },
      { text: "We state that to our knowledge the said property was originally owned and possessed by one __________________________ S/o. {{parentA}}, residing at {{addressA}}" },
      { text: "We, {{nameA}}, right or title or interest in the scheduled mentioned property." },
      { text: "We state that what are all the facts stated above are true to the best of my knowledge and I have not suppressed anything." },
      { text: "SCHEDULE OF PROPERTY", heading: true },
      { text: "All that piece and parcel of land situated in __________________________ District, __________________________ Sub-District, __________________________ Taluk, __________________________ Village, at present vadieesvaram north village in new survey No. __________________________ and at present new survey No. __________________________ in which {{executionDate}} ares equivalent to 3 cent __________________________ sq.ft. __________________________ 1 cent, __________________________ sq.ft. equivalent 62.__________________________ sq.mt. Plot in __________________________ corporation 38th ward within the __________________________ koil, neerali street, as mentioned above New survey R6/29 at present town survey land register New survey No. __________________________" },
      { text: "Solemnly affirmed at __________________________ |" },
      { text: "on this the day of August| BEFORE ME" },
      { text: "__________________________ and signed his name in |" },
      { text: "my presence.|" },
      { text: "1." },
      { text: "2." },
      { text: "DEPONENT: __________________________", heading: true },
    ],
  },
  "affidavit-no-proceedings": {
    id: "affidavit-no-proceedings",
    baseType: "deed",
    name: "Affidavit — No Case or Disciplinary Proceedings",
    deedTitle: "AFFIDAVIT",
    roleA: "DEPONENT",
    roleB: "",
    description: "Declares no civil, criminal or disciplinary proceedings are pending. Usual for appointments and licences.",
    body: [
      { text: "AFFIDAVIT", heading: true },
      { text: "I, {{nameA}} S/O {{parentA}} aged ___ years, residing at {{addressA}} , do hereby solemnly affirm and state as follows," },
      { text: "I am deponent herein." },
      { text: "That I am not involved in any civil / criminal / case / proceedings / charges / enquiry prior." },
      { text: "That I am not involved in any Disciplinary / malpractices / and / or any other charges / proceedings /enquiry / case pending against me in any organization / concern were I work previously." },
      { text: "I declare that the above facts are true and correct to the best of my knowledge." },
      { text: "Solemnly affirm and signed Deponent" },
      { text: "In my presence on this 17th day of" },
      { text: "November, __________________________ at __________________________ Before Me" },
    ],
  },
  "affidavit-gst-records": {
    id: "affidavit-gst-records",
    baseType: "deed",
    name: "Affidavit cum Declaration — GST Records",
    deedTitle: "AFFIDAVIT CUM DECLARATION",
    roleA: "DEPONENT",
    roleB: "",
    description: "To update the GST system with a change of business address or the nature of services supplied.",
    body: [
      { text: "AFFIDAVIT cum DECLARATION" },
      { text: "Request for updating the GST records" },
      { text: "I, {{nameA}}, aged ___ years now operating at my permanent residence at {{addressA}} , do hereby solemnly affirm and sincerely declare on oath through this Affidavit as follows:" },
      { text: "I provide business and financial advisory services primarily of capital nature such as raising of capital or mergers and acquisition for corporates in my personal capacity; this affidavit is to inform the authorities concerned to obtain the GST registration for depositing the GST component in my services fee." },
      { text: "The very purpose of this declaration is to update the GST system about my business interest, address and type of professional services to be rendered." },
      { text: "The facts stated above are true to the best of my knowledge and belief." },
      { text: "Deponent" },
      { text: "(__________________________)", heading: true },
      { text: "Date: {{executionDate}}" },
    ],
  },
  "affidavit-minor-travel-consent": {
    id: "affidavit-minor-travel-consent",
    baseType: "deed",
    name: "Consent Affidavit — Educational Tour of a Minor",
    deedTitle: "CONSENT AFFIDAVIT AND SWORN DECLARATION",
    roleA: "PARENTS",
    roleB: "",
    description: "Both parents consent to a minor travelling abroad with the school, and authorise passport and visa steps.",
    body: [
      { text: "CONSENT AFFIDAVIT & SWORN DECLARTION", heading: true },
      { text: "(For Educational Tour of Minor Child to NASA, USA)", heading: true },
      { text: "We, {{nameA}}, (Aadhaar Card/Passport No.__________________________ ), Son of {{parentA}}, aged about __________________________ years, and Mrs. __________________________ (Aadhaar Card/Passport No.__________________________ ), Wife of Mr.__________________________ aged about __________________________ years, who are the Parents of __________________________ (Name of Child), residing at {{addressA}} , do hereby solemnly affirm and sincerely state as follows:" },
      { text: "We are the father and mother / natural guardians of our minor Son/Daughter __________________________ (holding Indian Passport No.__________________________ ), aged about __________________________ years, who is presently studying in __________________________ at __________________________ School of Excellence , __________________________ Chennai -__________________________ Tamil Nadu State, India," },
      { text: "We state that That __________________________ School of Excellence, __________________________ Chennai, is organising an Educational Tour for its students to NASA, United States of America (USA), and our above-named minor son/daughter is participating in the said educational tour." },
      { text: "We hereby give our full consent for our minor son/daughter __________________________ to travel to the United States of America (USA) as a part of the said educational tour organised by the school through the Travel Agency M/s. __________________________ India __________________________" },
      { text: "We further state that we have no objection whatsoever for the school authorities or their authorised representatives to take all necessary steps and complete all formalities on behalf of our minor daughter/Son , including but not limited to:" },
      { text: "Application for Passport, Visa, and related documentation" },
      { text: "__________________________ permissions from Indian and foreign authorities" },
      { text: "Travel arrangements, accommodation, and educational visits" },
      { text: "Medical formalities, if any, during the course of the tour" },
      { text: "We authorise the School __________________________ / Tour __________________________ / __________________________ /Travel Agent to act as responsible person during the entire duration of the educational tour, including travel, stay, and return journey." },
      { text: "We further declare that we shall be fully responsible for all expenses, documentation, and compliance with laws, rules, and regulations applicable in India and the USA relating to our minor child." },
      { text: "This affidavit is executed to be produced before the School __________________________ Passport Office, Visa __________________________ __________________________ and any other concerned authorities, wherever required." },
      { text: "We affirm that the statements made above are true and correct to the best of our knowledge, belief, and information." },
      { text: "In view of the foregoing statements made in this affidavit, we humbly pray that the concerned authorities, including the Passport __________________________ Visa __________________________ __________________________ __________________________ and all other relevant authorities, may be pleased to grant the necessary permissions, visa, and approvals to enable our minor child to travel to NASA, United States of America (USA), along with the school authorities, and thus render justice." },
      { text: "1." },
      { text: "2." },
      { text: "Solemnly affirmed at __________________________ this __________________________ day of __________________________ of Deponent." },
      { text: "We, the above-named deponents, do hereby verify that the contents of this affidavit are true and correct to the best of our knowledge and belief and nothing material has been concealed therefrom." },
      { text: "__________________________ at Chennai, India on this __________________________ day of __________________________" },
      { text: "1." },
      { text: "2." },
      { text: "Signature of Deponent" },
      { text: "Before me." },
    ],
  },
  "affidavit-lost-land-document": {
    id: "affidavit-lost-land-document",
    baseType: "deed",
    name: "Affidavit — Lost Land Document",
    deedTitle: "AFFIDAVIT",
    roleA: "DEPONENT",
    roleB: "",
    description: "For an original registered title document that has been mislaid, with the search and the police complaint recorded.",
    body: [
      { text: "AFFIDAVIT", heading: true },
      { text: "I, {{nameA}} , Son / Daughter / Wife of {{parentA}} , aged ___ years, residing at {{addressA}} do hereby solemnly affirm and state as follows:" },
      { text: "I am the absolute owner / sole lawful holder of the piece and parcel of vacant plot bearing Plot No __________________________ with an extent of __________________________ Sq Feet in the __________________________ Survey No (S) 314/2, 314/3 & 314/8A situated at __________________________ Village ,__________________________ Taluk, __________________________ District with in the registration district of __________________________ and Sub registration district of __________________________" },
      { text: "The original registered document relating to the above property, namely:" },
      { text: "Document No __________________________ / __________________________ /Block 1/__________________________ / __________________________ Year: 2006__________________________ Registered at: __________________________ Sub-Registrar Office" },
      { text: "has been lost / misplaced by me." },
      { text: "I state that while carrying the document for official purposes such as xerox, consultation, patta transfer, property tax related work and other property-related activities, the said original document was inadvertently lost / misplaced." },
      { text: "In particular I took xerox of totally 6 land documents on 12th May at 3 pm in __________________________ Xerox shop , __________________________ , Chennai – 600 037 opposite to __________________________ chance of missing at this place is high as all documents mixed." },
      { text: "On {{executionDate}} I noticed only this document alone is missing , I made diligent search for the said document at all possible places, but I am unable to trace the same till date." },
      { text: "I have lodged a complaint regarding the loss of the document before V7 __________________________ Police Station with the Inspector of Police ." },
      { text: "I further state that the said original document has not been pledged, mortgaged, deposited, transferred or otherwise dealt with by me in favour of any person, bank or financial institution." },
      { text: "In the event the original document is traced in future, I undertake to produce the same before the appropriate authority if required." },
      { text: "I am executing this affidavit to place the true facts on record and for the purpose of obtaining certified copies and for future reference." },
      { text: "Solemnly affirmed at __________________________ this 23rd day of __________________________" },
      { text: "DEPONENT", heading: true },
      { text: "(Signature)", heading: true },
      { text: "Before Me" },
    ],
  },
  "affidavit-sponsorship": {
    id: "affidavit-sponsorship",
    baseType: "deed",
    name: "Affidavit of Sponsorship",
    deedTitle: "AFFIDAVIT OF SPONSORSHIP",
    roleA: "SPONSORS",
    roleB: "",
    description: "Parents undertake to meet a student's tuition, living costs and airfare abroad. Asked for by universities and consulates.",
    body: [
      { text: "AFFIDAVIT OF SPONSORSHIP", heading: true },
      { text: "We, {{nameA}}, aged ___ years, Parent of" },
      { text: "the Student, Indian Inhabitant, presently residing at {{addressA}}" },
      { text: "__________________________ COLONY, __________________________ NAGAR __________________________ CHENNAI-__________________________ TAMIL", heading: true },
      { text: "NADU State, India does hereby solemnly and sincerely affirm and state that: -" },
      { text: "Our son __________________________ is seeking to take admission in __________________________" },
      { text: "UNIVERSITY, __________________________", heading: true },
      { text: "We hereby undertake the responsibility to sponsor his total cost of tuition fees, books and" },
      { text: "supplies, medical insurance, living expenses and ‘to and from’ Air fare and all other expenses" },
      { text: "for his stay in abroad." },
      { text: "Furthermore, we confirm that we have taken an educational loan from __________________________ , Loan A/c" },
      { text: "No. L1__________________________ to cover the expenses related to his Master’s studies as stated above." },
      { text: "In addition, we have adequate financial resources from our assets and fixed deposits (__________________________)," },
      { text: "__________________________ Interest and liquid assets to further support our son’s education in __________________________" },
      { text: "combined financial arrangements ensure that all his educational and living expenses abroad" },
      { text: "will be fully covered without any difficulty." },
      { text: "We declare that whatever is stated above is true to the best of my knowledge and belief. We" },
      { text: "know that, to make a false affidavit is a criminal offense." },
      { text: "Place:" },
      { text: "Date:" },
      { text: "(a)", heading: true },
      { text: "Signature:__________________________" },
      { text: "(b)__________________________ by:", heading: true },
      { text: "Dated:__________________________ :__________________________" },
      { text: "Solemnly affirmed before me by" },
      { text: "__________________________ :__________________________" },
      { text: "Who has been identified by" },
      { text: "__________________________ :__________________________" },
      { text: "Who is personally known to me" },
      { text: "__________________________ DOCUMENTS", heading: true },
    ],
  },
  "affidavit-gas-name-change": {
    id: "affidavit-gas-name-change",
    baseType: "deed",
    name: "Affidavit — Change of Name on a Gas Connection",
    deedTitle: "AFFIDAVIT FOR CHANGE OF NAME",
    roleA: "DEPONENT",
    roleB: "",
    description: "Transfers a domestic gas connection into a spouse's name.",
    body: [
      { text: "AFFIDAVIT FOR CHANGE OF NAME", heading: true },
      { text: "(HUSBAND TO WIFE)", heading: true },
      { text: "From, Date: {{executionDate}}" },
      { text: "__________________________ (W/O __________________________ P)", heading: true },
      { text: "Door No. __________________________ B2 Block, Phase – 1," },
      { text: "__________________________ Apartments, 4th main road," },
      { text: "__________________________ Chennai - __________________________" },
      { text: "To," },
      { text: "__________________________ GAS AGENCIES", heading: true },
      { text: "H-915, 6th Avenue, Anna Nagar West, Chennai – __________________________" },
      { text: "GSTIN: 33__________________________ B1__________________________", heading: true },
      { text: "__________________________ /Madam," },
      { text: "Sub: Regarding gas connection name transfer" },
      { text: "I Mrs. __________________________ (W/O __________________________ P), aged ___ years, resident of India and occupied as homemaker hereby solemnly oath below:" },
      { text: "1. That my husband (late Mr. __________________________ P) had a __________________________ Gas Connection from __________________________ GAS AGENCIES, __________________________ and Subscription Voucher (__________________________) No. __________________________ dated {{executionDate}}" },
      { text: "2. That my husband Mr. __________________________ P has expired on {{executionDate}}." },
      { text: "3. That I request M/s __________________________ __________________________ to transfer the aforesaid connection in my name and allot me fresh consumer number." },
      { text: "4. That I indemnify M/s. __________________________ __________________________ and __________________________ GAS AGENCIES, __________________________ from any future claims raised by anybody in respect of the above requested change of name in __________________________ gas connection." },
      { text: "5. That in the event of any claims whatsoever, raised by anybody against the transfer of above referred connection in my name, I shall immediately surrender the equipment issued to me in respect to M/s __________________________ __________________________ unconditionally." },
      { text: "6. That I also confirm that I or any member of my family, as detailed in my ration card, do not possess any __________________________ connection from any Oil company." },
      { text: "…Continued on page 2" },
      { text: "7. That the original Subscription Voucher of __________________________ P is lost/misplaced and it is not traceable. If it is found in future, I will handle it to M/s __________________________ __________________________ without using it anywhere for any purpose." },
      { text: "8. That the legal heirs of late __________________________ P have appended their signatures below expressing their No Objection for the above requested transfer of the __________________________ gas connection." },
      { text: "9. That there are no more legal heirs of late __________________________ P other than those appending their signatures below." },
      { text: "Solemnly affirmed by the within named at on the day of {{executionDate}}." },
      { text: "__________________________ (__________________________ & __________________________ ) - We do not have any objection for transferring the __________________________ gas connection from late __________________________ P (Father) to __________________________ S (Mother) as requested above." },
      { text: "NAME", heading: true },
      { text: "1. __________________________", heading: true },
      { text: "(Relationship - Daughter)", heading: true },
      { text: "2. __________________________", heading: true },
      { text: "(Relationship - Daughter)", heading: true },
      { text: "__________________________ that the contents of above paras 1 to 9 are true and correct to the best of my knowledge and belief. I am liable u/s 193,199,200 of __________________________ /__________________________ if any contents found false." },
      { text: "Deponent" },
      { text: "(__________________________)", heading: true },
    ],
  },
  "affidavit-non-criminal-gap": {
    id: "affidavit-non-criminal-gap",
    baseType: "deed",
    name: "Affidavit — No Criminal Record and Study Gap",
    deedTitle: "AFFIDAVIT",
    roleA: "DEPONENT",
    roleB: "",
    description: "An employer's background-check undertaking: no criminal record, and an account of the gap since the last course.",
    body: [
      { text: "Whereas I, {{nameA}}, an adult Indian Inhabitant, residing at" },
      { text: "__________________________ have been selected by __________________________" },
      { text: "Services __________________________ (“__________________________ ”), , for employment as __________________________ vide Offer Letter dated __________________________ subject to" },
      { text: "the terms and conditions mentioned therein and subsequent acceptance of the offer letter by me" },
      { text: "and the submission of the BGC documents to __________________________" },
      { text: "And whereas since there has been a time gap after completion of my __________________________ /__________________________ degree course and the" },
      { text: "date of joining __________________________ has called upon me to give the following undertaking as part of" },
      { text: "Background Check Process, which I hereby do:" },
      { text: "I HEREBY __________________________ THE __________________________ UNDERTAKING:", heading: true },
      { text: "1. That I am not involved in any Civil / Criminal / case / proceedings / charges / enquiry prior" },
      { text: "to joining __________________________" },
      { text: "2. That I am not involved in any Disciplinary / malpractices and / or any other charges /" },
      { text: "proceedings / enquiry / case pending against me in any University or any other" },
      { text: "educational authority / institution prior to joining __________________________" },
      { text: "3. That I was not employed gainfully and / or honorary in any Organization, including Private" },
      { text: "/ Public / Government / Educational Institution etc., prior to joining __________________________" },
      { text: "3. That I was employed gainfully and / or honorary with __________________________ prior to joining __________________________ The" },
      { text: "particulars of my employment and reasons for leaving are as follows." },
      { text: "__________________________ The formal release letter from my said employer is attached" },
      { text: "hereto." },
      { text: "4. That whatever is stated above is true to my knowledge and belief and that no part of it is" },
      { text: "false. I shall be fully responsible and liable for all my acts or omissions." },
      { text: "5. That in case the above undertakings are found to be false, __________________________ shall be within its rights to" },
      { text: "forthwith terminate my services without any liability and take such legal recourse / actions" },
      { text: "against me as it may be advised." },
      { text: "6. That I shall fully indemnify and protect __________________________ from and against any acts or omissions" },
      { text: "attributable to me for breach hereof or otherwise, including, but not limited to, any loss," },
      { text: "damage, or liability suffered by __________________________ and / or civil or criminal action against __________________________ for" },
      { text: "reasons hereof." },
      { text: "IN WITNESS __________________________ I have put my signature on this undertaking on this __________________________ day of __________________________" },
      { text: "Signature of the Candidate:" },
      { text: "Name of the Candidate:" },
      { text: "__________________________ Offer Reference No:" },
      { text: "Place:" },
      { text: "Date:" },
      { text: "1. Witness:" },
      { text: "Signature of the Witness:" },
      { text: "Name:" },
      { text: "Address:" },
      { text: "Place:" },
      { text: "Date:" },
      { text: "2. Witness:" },
      { text: "Signature of the Witness:" },
      { text: "Name:" },
      { text: "Address:" },
      { text: "Place:" },
      { text: "Date:" },
    ],
  },
};

export const AFFIDAVIT_TEMPLATE_IDS = Object.keys(AFFIDAVIT_TEMPLATES) as AffidavitTemplateId[];
