import type { DeedTemplate } from "./deed-templates";

/**
 * Seven more documents the office supplied, held verbatim.
 *
 * Four agreements for sale — a plot, a flat, a long form for a sale worth
 * arguing about, and a salvage vehicle sold as it stands — a supplier's
 * corporate guarantee, and the memorandum of deposit of title deeds in the two
 * bank forms the office uses.
 *
 * All seven arrived executed. Between them they carried names, Aadhaar and PAN
 * numbers, home addresses, survey and door numbers, a vehicle registration with
 * its engine and chassis numbers, an insurance policy number, a purchase order
 * number and the sums involved. Every one of those is now either a {{token}}
 * the form fills or a blank rule the counter completes.
 *
 * Amounts are deliberately left as rules wherever a document names more than
 * one. A sale agreement states a consideration, an advance and a balance, and
 * pouring a single answer into all three would print a deed that contradicts
 * itself. Only the two documents that name a single sum ask for it.
 */

export type ContractTemplateId =
  | "sale-agreement-land"
  | "sale-agreement-flat"
  | "sale-agreement-detailed"
  | "sale-damaged-vehicle"
  | "corporate-guarantee"
  | "mod-title-deeds"
  | "mod-title-deeds-bank"
  ;

export const CONTRACT_TEMPLATES: Record<ContractTemplateId, DeedTemplate> = {
  "sale-agreement-land": {
    id: "sale-agreement-land",
    baseType: "sale",
    name: "Agreement for Sale — Land",
    deedTitle: "AGREEMENT FOR SALE",
    roleA: "VENDOR",
    roleB: "PURCHASER",
    description: "An agreement to sell a plot ahead of the sale deed — price, advance, the time to complete, and what happens if either side walks away.",
    body: [
      { text: "AGREEMENT FOR SALE", heading: true },
      { text: "This deed of agreement for sale executed at Chennai on this the __________________________ day of August __________________________" },
      { text: "BETWEEN", heading: true },
      { text: "Mr. {{nameA}}, wife of {{parentA}} (Aadhaar No), (PAN No.) aged ___ years, residing at {{addressA}} hereinafter referred to as the VENDOR which term shall been and include wherever the context so requires or permit her heirs, legal representatives, executors, administrators, nominees and assigns of the ONE PART." },
      { text: "AND", heading: true },
      { text: "Mr. {{nameB}}, Son of {{parentB}} (Aadhaar No. {{aadhaarB}}) (PAN No. __________________________ ) aged ___ years, residing at {{addressB}} hereinafter referred to as the PURCHASER which term shall mean and include wherever the context so requires or permits his legal heirs, legal representatives, executors, administrators, nominees and assigns of the OTHER PART." },
      { text: "The terms VENDOR and PURCHASER wherever the context so appears, shall mean and include them, their respective heirs, executors, administrators and assigns __________________________ as follows :-" },
      { text: "WHEREAS the VENDOR herein is the absolute owner of the vacant land bearing Plot No. __________________________ approved layout comprised in __________________________ 54 (part) and 55 (part) as per Patta No: __________________________ new S. No: __________________________ in __________________________ Village, presently __________________________ Taluk, Tiruvallur District in Chennai Metropolitan Development Authority’s approved layout No: __________________________ Lo. No: __________________________ measuring an extent of __________________________ (230.4 sq.meter) (2.30 ares) morefully described in the schedule hereunder as schedule of property." },
      { text: "Whereas the VENDOR is the sole and absolute owner of the schedule mentioned property and she purchased the same fiom the Chennai Metropolitan Co-Operative Housing Society Limited No: __________________________ a Co-op Housing Society Registered under Co-op __________________________ Act of __________________________ and now governed by the Tamil Nadu Co-Operative __________________________ Act __________________________ (Act 30 of __________________________ ) having its office at __________________________" },
      { text: "Whereas the VENDOR herein thus became the absolute owner of the schedule property and the VENDOR has been issued with Patta bearing No: __________________________" },
      { text: "Whereas the VENDOR is in absolute possession and enjoyment of the schedule property even since the date of purchase." },
      { text: "Whereas the VENDOR has agreed to sell the schedule property morefully described in the schedule hereunder and the PURCHASER has agreed to purchase the same measuring an extent of __________________________ vacant land for a total sale consideration of Rs. __________________________ /- (Rupees __________________________ only) free from all encumbrances." },
      { text: "Whereas the VENDOR and the PURCHASER has mutually agreed to complete the sale transaction of the schedule property on the following terms and conditions." },
      { text: "NOW THIS __________________________ FOR SALE __________________________ THAT", heading: true },
      { text: "1.In consideration of the above recitals and in consideration of the sum of Rs. __________________________ /- (Rupees __________________________ only) agreed to be paid by the PURCHASER to the VENDOR, the VENDOR hereby agreed to sell to the PURCHASER or his nominee or nominees by way of an absolute sale of all that piece and parcel of the vacant land to an extent of __________________________ comprised in S. No.54 (part) and 55 (part) as per Patta No: __________________________ new __________________________ No: __________________________ Plot No. __________________________ in the __________________________ approved by __________________________ by order No: __________________________ No: __________________________ comprised in __________________________ Village, presently __________________________ Taluk, Tiruvallur District morefully described in the schedule hereunder as schedule of property together with all other rights, previleges, liberties and appurtenances thereto." },
      { text: "2.The PURCHASER has this day paid a sum of Rs. __________________________ /- (Rupees __________________________ only) as advance to the VENDOR in the following manner :-" },
      { text: "A cheque bearing No: __________________________ dated __________________________ for a sum of Rs. __________________________ /- (Rupees __________________________ only) drawn on the __________________________ Bank of __________________________ Branch." },
      { text: "3.The PURCHASER agrees to pay the balance sale consideration of a sum of Rs. __________________________ /- (Rupees __________________________ only) at the time of registration of the sale deed. The sale shall be completed within 2 months from the date of signing this sale agreement" },
      { text: "4.The VENDOR agree to arrange/sign/execute/furnish all deeds/documents/papers and do all such acts, deed, things which may be necessary in law for better assurance of title to the __________________________ for the property agreed to be conveyed herein." },
      { text: "5.The VENDOR further convents with the __________________________ that the property is free from encumbrances, and loan, prior agreement to sell or any claim, or lis pendens, or acquisition proceeding of State/Central Government and absolute/dispositive/marketable title vests with the VENDOR." },
      { text: "6.The VENDOR hereby covenants that the VENDOR has not entered into any agreement of sale or any arrangement of whatsoever in nature with any other party either herself to sell the property and shall indemnify the __________________________ against the claim by any person or persons claiming to have title in the property or a right to purchase the same or from any other claim made by any other person whatsoever." },
      { text: "7.The VENDOR has also represented that the VENDOR is the absolute owner of the scheduled property and is entitled to enter into this agreement for sale and also execute and register necessary sale deed in favour of the __________________________ for sale of the schedule mentioned property and receive the sale consideration therefore in the manner set out in this agreement. Except the VENDOR, no other person has any title, interest, manner or right whatsoever over the schedule mentioned property." },
      { text: "8.The VENDOR has represented that she has not received any notice under any act from any person or bank or authority so as to affect the sale of the schedule property. The VENDOR has represented that the schedule property is not the subject of any Arbitration or Conciliation proceedings, and there is no court order that would affect the sale of the schedule property to the __________________________ in any manner." },
      { text: "9.The VENDOR has represented that no notice has been received under the securitization and Reconstruction of Financial Assets and Enforcement of Security Interest Act or Ordinance and that there is no scope for the schedule property being proceeded against, by any bank or institution. The schedule property is not a financial asset or secured asset with any bank institution. There is no scope for taking possession or custody of the schedule property by any bank or institution and there is no priority or charge in favour of any workman of the VENDOR." },
      { text: "10.The VENDOR agreed to execute and register all necessary documents, sale deeds, rectification deeds, ratification deeds, declarations, affidavits and undertakings and all other papers and forms as may be required by the __________________________ for the sale of the property in favour of the __________________________ for better assuring the title of the __________________________ after schedule property the sale has been effected." },
      { text: "11.The VENDOR agrees to execute and register necessary receipts for all payments made by the __________________________" },
      { text: "12.The parties may be mutual consent alter, modify or change the terms of this agreement by exchange of communication in writing." },
      { text: "SCHEDULE OF PROPERTY", heading: true },
      { text: "All that piece and parcel of the vacant house site land in Plot No. __________________________ in __________________________ approved layout __________________________ approved layout No: __________________________ Lo. No: __________________________ to an extent of __________________________ Sq,ft (230.4 sq.meter) comprised in S. No.54 (part) and 55 (part) as per patta No: __________________________ new __________________________ No: __________________________ at __________________________ Village presently __________________________ Taluk, Tiruvallur District." },
      { text: "Bounded on the" },
      { text: "North : 12.0 meters (__________________________ feet)" },
      { text: "South : 12.0 meters (__________________________ feet)" },
      { text: "East : 19.0 meters (__________________________ feet)" },
      { text: "West : 19.4 meters (63 ½ feet)" },
      { text: "In all measuring 230.4 sq.meter (__________________________ sq.ft) vacant land situated within the registration district of Chennai South and Sub Registration District of Joint-II, __________________________" },
      { text: "Market value of the land is Rs. __________________________ /- There is no building in the site." },
      { text: "In witnesses whereof the parties hereinto set their hands and signature on the day, month and year first above written in the presence of" },
      { text: "Purchaser Vendor" },
      { text: "Witnesses" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
    ],
  },
  "sale-agreement-flat": {
    id: "sale-agreement-flat",
    baseType: "sale",
    name: "Agreement for Sale — Flat or Apartment",
    deedTitle: "AGREEMENT FOR SALE",
    roleA: "VENDOR",
    roleB: "PURCHASER",
    description: "For a flat or apartment with its undivided share of land, association dues and the vendor's warranties on title.",
    body: [
      { text: "AGREEMENT FOR SALE", heading: true },
      { text: "THIS AGREEMENT OF SALE made at Chennai on this __________________________ day of DECEMBER __________________________ Between Mr. {{nameA}} (Aadhar Id : {{aadhaarA}}, PAN : __________________________ ), S/o. {{parentA}} aged ___ years residing at {{addressA}} hereinafter referred to as “VENDOR\" which expression shall, wherever the context so requires or admits, mean and include, his heirs, executors, administrators and assigns of the ONE PART;" },
      { text: "TO AND IN FAVOUR OF", heading: true },
      { text: "Mr. {{nameB}} (Aadhaar No. {{aadhaarB}}, PAN : __________________________ ), Son of {{parentB}} aged ___ years residing at {{addressB}} hereinafter referred to as the “PURCHASER\", which expression shall, wherever the context so requires or admits, mean and include its successors in title and assigns of the OTHER PART; The VENDOR and the PURCHASER are hereinafter collectively referred to as “Parties” and individually “Party”." },
      { text: "__________________________ AS FOLLOWS:-", heading: true },
      { text: "WHEREAS the VENDOR is the absolute owner of All that piece and parcel of Residential Flat bearing Flat No. __________________________ First Floor with super built up area of __________________________ Feet in the building complex know as WIDE WING Apartment together with __________________________ Feet undivided share of land out of __________________________ Feet along with a car park (morefully described in Schedule of Property) having purchased the same From __________________________ by way of Sale Deed dated {{executionDate}} bearing Document No. __________________________ of __________________________ I __________________________ And Subsequently entered into an Construction Agreement for the construction of the said Flat." },
      { text: "WHEREAS the Vendor is desirous of selling the Schedule Property and had offered the same to the PURCHASER by assuring, representing, and warranting to the PURCHASER herein the following: The Vendor herein is the sole and absolute owner of Schedule Property and that the title to the respective property set out in the Schedule hereto is good, valid, marketable and subsisting and none else has any right, title, interest or share therein of the Vendor; a) The Schedule of Property or any part thereof is not subject to any encumbrances, attachments, Court or acquisition proceedings or charges of any kind; b) The Vendor have not received any notice or orders issued under any Ordinance/Act/Statute/Rules or Regulations (State or Central) affecting the Schedule Property or any part thereof or the sale thereof; c) The Vendor is entitled to sell and dispose off Schedule Property;" },
      { text: "WHEREAS based on the aforesaid representations, the PURCHASER have agreed to purchase the Schedule Property from the Vendor herein and the Parties hereto are now desirous of reducing the terms agreed into writing in terms hereof;" },
      { text: "NOW THIS AGREEMENT OF SALE WITNESSES AS FOLLOWS:", heading: true },
      { text: "That in pursuance of the foregoing and in consideration of the price hereby agreed to be paid in the manner set out herein, the VENDOR offers the Schedule Property for sale, and the PURCHASER hereby agrees to purchase Schedule Property subject, to the following terms and conditions:-" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "The PURCHASER shall bear and pay the expenses relating to Stamp duty, registration and conveyance charges in regard to the Deed of Sale of the Schedule Property;" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "This Agreement constitutes the entire Agreement between the Parties, and supersedes all other Agreements and understandings between the Parties or any of them;" },
      { text: "__________________________   __________________________" },
      { text: "The headings of the paragraphs of this Agreement are inserted for convenience of reference only and are not intended to be part of or to affect the meaning or interpretation of this Agreement;" },
      { text: "SCHEDULE OF THE PROPERTY", heading: true },
      { text: "__________________________   __________________________" },
      { text: "BOUNDED ON THE", heading: true },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "IN WITNESS WHEREOF the parties have set their hands to this Agreement on the day and year first hereinabove written." },
      { text: "PURCHASER/ Other Part Vendor /First Part __________________________ ;" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
    ],
  },
  "sale-agreement-detailed": {
    id: "sale-agreement-detailed",
    baseType: "sale",
    name: "Agreement for Sale — Detailed",
    deedTitle: "AGREEMENT FOR SALE",
    roleA: "SELLER",
    roleB: "BUYER",
    description: "The long form, for a sale worth arguing about: representations, encumbrance searches, default, specific performance and the handover schedule.",
    body: [
      { text: "AGREEMENT FOR SALE", heading: true },
      { text: "This AGREEMENT FOR SALE (“Agreement”) is made and executed at Chennai on this {{executionDate}} (“Execution Date”)," },
      { text: "BY AND BETWEEN", heading: true },
      { text: "Mr. {{nameA}}, S/o. {{parentA}}, aged ___ years holding Aadhaar No. {{aadhaarA}} and PAN __________________________ residing at {{addressA}} hereinafter referred to as the “SELLER/VENDOR” (which expression shall, unless repugnant to the context or meaning thereof, be deemed to mean and include his legal heirs, executors, administrators, legal representatives and assigns) of the ONE PART;" },
      { text: "AND", heading: true },
      { text: "Mr. {{nameB}}, aged ___ years, holding PAN __________________________ and Aadhaar No. {{aadhaarB}}; and Mrs. __________________________ B, Wife of {{parentB}} aged ___ years, holding PAN __________________________ and Aadhaar No. {{aadhaarB}}, both residing at {{addressB}} hereinafter jointly and severally referred to as the “BUYERS/PURCHASERS” (which expression shall, unless repugnant to the context or meaning thereof, be deemed to mean and include their respective legal heirs, executors, administrators, legal representatives and permitted assigns) of the OTHER PART." },
      { text: "The Seller and the Buyers are hereinafter collectively referred to as the “Parties” and individually as a “Party”." },
      { text: "The Buyers shall jointly purchase the __________________________ Property and shall hold the same in equal shares, i.e., 50% (fifty per cent) undivided right, title and interest each." },
      { text: "WHEREAS the Seller is the absolute and lawful owner of undivided share of land admeasuring __________________________ sq.ft. out of a total extent of __________________________ comprised in Survey No __________________________ Survey No __________________________ Survey No. __________________________ (Survey No __________________________ as per sub-division) and Survey No __________________________ (Survey No __________________________ as per sub-division), situated at __________________________ Village, __________________________ Taluk, __________________________ District (now known as No. 61, __________________________ , __________________________ Nagar, __________________________ West, Chennai – __________________________ ), together with a residential flat bearing Flat No. __________________________ on the Second Floor of B-Block in the apartment complex known as “Sunstone Apartments”, having a super built-up area of about 1,__________________________ sq.ft. (including 22% common area), together with a covered car parking space bearing No: __________________________ in the stilt floor of B-Block, with all rights, amenities, fittings and appurtenances thereto, more fully described in the Schedule of Property hereunder (“__________________________ Property”), having purchased the undivided share of land under a registered Deed of Sale dated {{executionDate}} registered as Document No __________________________ of __________________________ on the file of the Sub-Registrar, __________________________ and having got the said flat constructed pursuant to a Builders Agreement dated {{executionDate}} entered into with M/s. __________________________ & Ramesh Builders;" },
      { text: "AND WHEREAS the Seller represents that he is in lawful, peaceful and uninterrupted possession and enjoyment of the __________________________ Property and that the same is free from all encumbrances, charges, liens, mortgages, attachments, claims, litigation, acquisition proceedings and third-party rights whatsoever, save and except such as may be specifically disclosed by the Seller to the Buyers in writing prior to execution hereof." },
      { text: "AND WHEREAS the Seller is desirous of selling the __________________________ Property and the Buyers, being husband and wife, are desirous of jointly purchasing the same, in equal shares of 50% (fifty per cent) each, for their own use and benefit;" },
      { text: "AND WHEREAS the Parties have agreed that the total sale consideration for the __________________________ Property shall be Rs. __________________________ /- (Rupees __________________________ only);" },
      { text: "AND WHEREAS the Buyers have, on or before the execution of this Agreement, paid to the Seller a sum of Rs. __________________________ /- (Rupees __________________________ only) as advance/earnest money, the payment and receipt whereof the Seller hereby acknowledges, and the Parties have agreed that the balance sale consideration of Rs. __________________________ /- (Rupees __________________________ only) shall be paid by the Buyers to the Seller on or before {{executionDate}}." },
      { text: "AND WHEREAS the Parties have agreed that the Seller shall execute and register the absolute Sale Deed in respect of the __________________________ Property in favour of the Buyers upon receipt of the entire balance sale consideration and fulfilment of the other terms and conditions recorded herein;" },
      { text: "NOW THEREFORE, THIS AGREEMENT __________________________ AND THE PARTIES HERETO AGREE AS FOLLOWS:" },
      { text: "OPERATIVE CLAUSES", heading: true },
      { text: "1. Agreement to Sell" },
      { text: "The Seller hereby agrees to sell, and the Buyers hereby agree to jointly purchase, the __________________________ Property, free from all encumbrances, for the total sale consideration of Rs. __________________________ /- (Rupees __________________________ only), on the terms and conditions contained in this Agreement." },
      { text: "2. Sale Consideration" },
      { text: "The total sale consideration agreed between the Parties for the sale of the __________________________ Property is Rs. __________________________ /- (Rupees __________________________ only), payable in the manner set out in Clauses 3 and 4 below." },
      { text: "3. Advance Payment" },
      { text: "The Buyers have paid to the Seller, and the Seller hereby acknowledges receipt of, a sum of Rs. __________________________ /- (Rupees __________________________ only) as advance/earnest money towards the sale consideration, paid on {{executionDate}} by way of Cheque bearing instrument no.__________________________ Bank : __________________________ Bank, __________________________ Nagar Branch" },
      { text: "4. Balance Payment" },
      { text: "The Buyers shall pay to the Seller the balance sale consideration of Rs. __________________________ /- (Rupees __________________________ only) on or before {{executionDate}}, or earlier, by way of demand draft/pay order/__________________________ /__________________________ transfer to an account designated by the Seller in writing, time being of the essence of this Agreement." },
      { text: "5. Deduction of Tax at Source (TDS)" },
      { text: "Since the total sale consideration exceeds Rs. __________________________ /- (Rupees __________________________ only), the Buyers shall, at the time of credit or payment of the sale consideration (or any part thereof), whichever is earlier, deduct income-tax at source under Section 393(1) of the Income-tax Act, __________________________ (currently at 1% of the sale consideration, or such other rate as may be prescribed and in force on the date of payment) and shall remit the amount so deducted to the credit of the Central Government within the time prescribed under the Income-tax Act, __________________________ by filing Form No: __________________________" },
      { text: "The Buyers shall furnish to the Seller the TDS certificate in Form No. 132 within the time prescribed under the Income-tax Act,__________________________ The amounts payable by the Buyers to the Seller under Clauses 3 and 4 above shall stand reduced to the extent of the tax so deducted at source, and the Seller shall have no claim against the Buyers in respect of any amount so deducted and remitted in accordance with law. Each Buyer shall deduct and remit TDS in proportion to his/her respective 50% share of the sale consideration, unless the Parties otherwise agree and confirm in writing." },
      { text: "6. Execution and Registration of Sale Deed" },
      { text: "Upon receipt of the entire balance sale consideration in terms of Clause 4 above (net of TDS deducted under Clause 5) and upon the Buyers otherwise complying with their obligations under this Agreement, the Seller shall execute and register an absolute Sale Deed conveying the __________________________ Property in favour of the Buyers in equal shares of 50% (fifty per cent) each, before the concerned Sub-Registrar having jurisdiction, within a reasonable time not exceeding 30 (thirty) days of receipt of the entire balance consideration, or on/before {{executionDate}}, whichever is later, unless otherwise mutually agreed in writing." },
      { text: "7. Title Verification" },
      { text: "The Buyers and/or their advocate shall be entitled, within from the date of this Agreement, to inspect and verify the Seller’s title, the parent documents and other records relating to the __________________________ Property. The Seller shall extend full co-operation and make available all relevant original documents for such verification." },
      { text: "8. Delivery of Original Documents" },
      { text: "The Seller shall hand over to the Buyers all original title deeds, parent documents, tax receipts and other documents of title relating to the __________________________ Property in his possession, at the time of registration of the Sale Deed, or at such earlier stage as may be mutually agreed, subject to any documents genuinely required to be retained for other flats/co-owners under the common Builders Agreement being made available in copy with an undertaking to produce the originals when required." },
      { text: "9. Possession" },
      { text: "No instructions have been received as to when vacant, peaceful possession of the __________________________ Property will be handed over to the Buyers. Unless otherwise agreed in writing, it is recorded that possession shall be delivered by the Seller to the Buyers simultaneously with, or within a reasonable time after, execution and registration of the Sale Deed and receipt of full sale consideration, and not on the date of this Agreement." },
      { text: "10. Encumbrances" },
      { text: "The Seller shall, at his own cost, clear/discharge any encumbrance, charge, mortgage, lien or liability whatsoever affecting the __________________________ Property, whether disclosed or undisclosed, existing as on the date of registration of the Sale Deed, and shall keep the Buyers indemnified in respect thereof." },
      { text: "11. Taxes and __________________________" },
      { text: "All property tax, electricity charges, water/sewerage charges, maintenance charges payable to the association/M/s. Sunstone Apartment Owners Association and other statutory or local-authority dues in respect of the __________________________ Property up to and including the date of handing over of possession shall be borne and paid by the Seller. All such dues accruing from and after the date of possession shall be borne by the Buyers. The Seller shall produce paid-up receipts/no-dues certificates for all such outgoings up to the date of possession, at the time of registration." },
      { text: "12. Stamp Duty and Registration __________________________" },
      { text: "The stamp duty, registration fees and all other incidental costs and expenses for the preparation, stamping and registration of the Sale Deed shall be borne and paid entirely by the Buyers." },
      { text: "13. Default by Buyers" },
      { text: "If the Buyers commit default in payment of the balance sale consideration within the time stipulated in Clause 4, and such default continues for a further period of 30 days after written notice from the Seller calling upon the Buyers to make payment, the Seller shall be entitled, at his option and subject to applicable law, to either (a) forfeit the advance of Rs. __________________________ /- and terminate this Agreement, or (b) sue for specific performance together with damages, or (c) grant further time on such terms as may be mutually agreed. Any forfeiture shall be reasonable and proportionate and subject to the provisions of the Indian Contract Act, __________________________ and the Specific Relief Act, __________________________ as applicable." },
      { text: "14. Default by Seller" },
      { text: "If the Seller, despite the Buyers being ready and willing to perform their obligations under this Agreement (including tender of the balance sale consideration), fails or refuses or neglects to execute and register the Sale Deed in favour of the Buyers, or otherwise commits breach of this Agreement, the Buyers shall be entitled, at their option, to (a) seek specific performance of this Agreement together with damages, or (b) terminate this Agreement and claim refund of the entire advance of Rs. __________________________ /- together with reasonable damages/compensation as may be determined in accordance with law, or (c) pursue such other remedies as may be available under applicable law." },
      { text: "15. Specific Performance" },
      { text: "Nothing contained in this Agreement shall be construed to derogate from or limit either Party’s right to seek specific performance of this Agreement, or any other relief or remedy available to it under the Specific Relief Act, __________________________ or any other applicable law, in the event of breach by the other Party." },
      { text: "16. Indemnity" },
      { text: "The Seller shall keep the Buyers fully indemnified and held harmless against any loss, cost, damage, claim or liability suffered or incurred by the Buyers on account of any defect in the Seller’s title, any undisclosed encumbrance, charge, claim or lien, or any misrepresentation or suppression of material fact by the Seller in relation to the __________________________ Property." },
      { text: "17. Further __________________________" },
      { text: "Each Party shall, at the request and cost of the other Party (unless otherwise agreed), execute all such further deeds, documents and writings and do all such acts and things as may be reasonably necessary to give full effect to this Agreement and to complete the sale transaction contemplated herein, including any documents required by the builder/association of Sunstone Apartments or statutory authorities." },
      { text: "18. __________________________" },
      { text: "All notices, demands or other communications required or permitted to be given under this Agreement shall be in writing and shall be deemed to have been duly given if delivered by hand, registered post with acknowledgment due, or reputed courier, or e-mail (with proof of delivery), to the Seller at No. 11, __________________________ Street, __________________________ Nagar, __________________________ Tamil Nadu – __________________________ and to the Buyers at __________________________ 4, Sunstone Apartment, __________________________ Nagar, Ana Avenue, __________________________ West, Chennai – __________________________ or at such other address as either Party may notify to the other in writing from time to time." },
      { text: "19. Dispute Resolution / Jurisdiction" },
      { text: "The registration jurisdiction and Sub-__________________________ office for the __________________________ stated as North Chennai Registration District, __________________________ Sub-Registration District; this should be reconfirmed against current jurisdictional records at the time of registration. Subject to the foregoing, the Parties agree that this Agreement shall be governed by and construed in accordance with the laws of India, and that the courts/fora at Chennai, Tamil Nadu shall have exclusive jurisdiction over any dispute arising out of or in connection with this Agreement, without prejudice to the Parties’ right to refer disputes to arbitration or mediation if mutually agreed in writing." },
      { text: "20. Entire Agreement" },
      { text: "This Agreement constitutes the entire agreement between the Parties in relation to its subject matter and supersedes all prior discussions, negotiations, understandings or agreements, whether oral or in writing, between the Parties relating thereto." },
      { text: "21. Amendment" },
      { text: "No amendment, modification or waiver of any provision of this Agreement shall be valid or binding unless made in writing and duly signed by all the Parties hereto." },
      { text: "__________________________ REGISTRATION", heading: true },
      { text: "The Seller further undertakes and agrees that, from the date of this Agreement until registration of the Sale Deed, he shall:" },
      { text: "(a) maintain the __________________________ Property in substantially the same condition as on the date of this Agreement, ordinary wear and tear excepted;" },
      { text: "(b) not create, permit or suffer to be created any mortgage, charge, lien, lease, licence, tenancy, gift, or other third-party interest whatsoever over the __________________________ Property or any part thereof;" },
      { text: "(c) not sell, transfer, convey or otherwise deal with the __________________________ Property or any part thereof or interest therein with any person other than the Buyers;" },
      { text: "(d) forthwith disclose to the Buyers in writing any material litigation, notice, acquisition proceeding or governmental/statutory proceeding affecting the __________________________ Property that comes to his knowledge;" },
      { text: "(e) clear all outgoings and liabilities relating to the __________________________ Property as agreed under Clause 11 above; and" },
      { text: "(f) produce and make available all original documents of title reasonably required by the Buyers for title verification and for registration of the Sale Deed." },
      { text: "TERMINATION / CANCELLATION", heading: true },
      { text: "This Agreement may be terminated in the following circumstances, subject to applicable law:" },
      { text: "(a) Buyer’s Default: If the Buyers fail to pay the balance sale consideration as stipulated in Clause 4 and fail to cure such default within the notice period referred to in Clause 13, the Seller may terminate this Agreement in accordance with Clause 13. In such event, the advance of Rs. __________________________ /- may be forfeited by the Seller only to the extent reasonable and proportionate to the loss actually suffered, and subject to applicable law; it shall not be treated as an automatic or punitive forfeiture." },
      { text: "(b) Seller’s Default: If the Seller fails or refuses to complete the sale despite the Buyers being ready and willing to perform, the Buyers may terminate this Agreement in accordance with Clause 14, in which event the Seller shall refund the entire advance of Rs. __________________________ /- together with such compensation/damages as may be agreed or determined in accordance with law." },
      { text: "(c) Material Defect in Title: If, upon verification under Clause 7, a material and irremediable defect in the Seller’s title is discovered which the Seller is unable to cure within a reasonable time, the Buyers may terminate this Agreement, and the Seller shall refund the entire advance of Rs. __________________________ /- (and any part-payment made) without any deduction." },
      { text: "(d) Failure to __________________________ Agreed Conditions: If any condition precedent to registration set out in this Agreement is not fulfilled for reasons not attributable to either Party, the Parties may mutually agree to extend time or terminate this Agreement, in which case the advance shall be refunded in full unless otherwise agreed." },
      { text: "(e) Mutual Cancellation: This Agreement may be cancelled at any time by mutual consent of the Parties recorded in writing, on such terms regarding refund of the advance as the Parties may agree at that time." },
      { text: "IN WITNESS WHEREOF", heading: true },
      { text: "the Parties hereto have set their respective hands to this Agreement on the day, month and year first above written, in the presence of the following witnesses." },
      { text: "SELLER", heading: true },
      { text: "Name: Mr. V. __________________________" },
      { text: "Signature: __________________________" },
      { text: "__________________________   __________________________" },
      { text: "Name: Mr. __________________________" },
      { text: "Signature: __________________________" },
      { text: "__________________________   __________________________" },
      { text: "Name: Mrs. __________________________ B" },
      { text: "Signature: __________________________" },
      { text: "WITNESSES", heading: true },
      { text: "__________________________   __________________________" },
      { text: "Address: __________________________" },
      { text: "Signature: __________________________" },
      { text: "__________________________   __________________________" },
      { text: "Address: __________________________" },
      { text: "Signature: __________________________" },
      { text: "SCHEDULE OF PROPERTY", heading: true },
      { text: "SCHEDULE ‘A’ – __________________________ Extent of Land" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "SCHEDULE ‘B’ – Undivided Share of Land (Seller’s Title)" },
      { text: "__________________________   __________________________" },
      { text: "SCHEDULE ‘C’ – Property Hereby Agreed to be __________________________" },
      { text: "__________________________   __________________________" },
      { text: "KEY TRANSACTION SUMMARY", heading: true },
      { text: "Particulars" },
      { text: "Details" },
      { text: "Seller" },
      { text: "Mr. V. __________________________ S/o. Mr. G. __________________________" },
      { text: "__________________________   __________________________" },
      { text: "Mr. __________________________" },
      { text: "__________________________   __________________________" },
      { text: "Mrs. __________________________ B – Wife of Mr. __________________________" },
      { text: "Buyer Address" },
      { text: "__________________________   __________________________" },
      { text: "Total Sale Consideration" },
      { text: "__________________________   __________________________" },
      { text: "Advance Paid" },
      { text: "__________________________   __________________________" },
      { text: "Balance Payable" },
      { text: "__________________________   __________________________" },
      { text: "Balance Payment Deadline" },
      { text: "__________________________   __________________________" },
      { text: "Ownership Share" },
      { text: "__________________________   __________________________" },
      { text: "TDS", heading: true },
      { text: "__________________________   __________________________" },
      { text: "Stamp Duty & Registration __________________________" },
      { text: "__________________________   __________________________" },
      { text: "Property" },
      { text: "__________________________   __________________________" },
      { text: "Sale Deed" },
      { text: "To be executed and registered upon receipt of full consideration and fulfilment of agreed conditions" },
    ],
  },
  "sale-damaged-vehicle": {
    id: "sale-damaged-vehicle",
    baseType: "sale",
    name: "Agreement for Sale of a Damaged Vehicle",
    deedTitle: "AGREEMENT FOR SALE OF DAMAGE VEHICLE",
    roleA: "SELLER",
    roleB: "PURCHASER",
    description: "Selling a salvage vehicle as it stands — the buyer takes the condition, the transfer at the RTO, and everything that follows.",
    body: [
      { text: "Agreement for Sale of Damage Vehicle" },
      { text: "THIS AGREEMENT is made at Chennai on {{executionDate}}" },
      { text: "Between" },
      { text: "Mr. {{nameA}} Residing at {{addressA}}" },
      { text: "__________________________ Chennai – __________________________ (Hereinafter called 'the seller’) Party of the First Part" },
      { text: "And" },
      { text: "Mr. {{nameB}} residing at {{addressB}}" },
      { text: "__________________________ - __________________________ (Hereinafter called 'the Purchaser') Party of the Second Part;" },
      { text: "And whereas -" },
      { text: "1. I, __________________________ has got the Vehicle no. __________________________ insured against loss of his car, having Engine __________________________ and Chassis __________________________ under insurance Policy No __________________________ issued by __________________________ General Insurance __________________________ Ltd. for the period from {{executionDate}} till {{executionDate}} midnight as per terms and conditions laid down by __________________________" },
      { text: "And Whereas –" },
      { text: "2. The Seller __________________________ wanted to sell the said car as and where condition." },
      { text: "And Whereas –" },
      { text: "3. The Purchaser __________________________ approached the seller __________________________ and offered to purchase the said salvage car for the amount mentioned in the terms and condition." },
      { text: "NOW IT IS HEREBY AGREED AS FOLLOWS:--", heading: true },
      { text: "The insurer M/s. __________________________ General Insurance Company (India) Limited. has acted only as a facilitator to act on behalf of and assist __________________________ in the salvaging process." },
      { text: "The seller will sell the Car No __________________________ to the purchaser for the amount of Rs. {{amount}}/- (in words __________________________ )." },
      { text: "The Purchaser will purchase the said car in cash or issuing single Demand Draft of the amount agreed, payable either to the Hypothecator’s Loan A/c. Number (In case where Seller does not foreclose the loan and share Form-35 & NOC in Originals) or to the Seller (In case where Seller forecloses the loan and share Form-35 & NOC in Originals)" },
      { text: "The Purchaser will transfer the vehicle registration in the books of RTO within 90 days from the date of purchase and will bear the cost of the transfer fees, which is to be paid to the RTO." },
      { text: "The Purchaser will insure the car at his own cost and provide the copy of the insurance policy to the seller within 90 days of sale/purchase." },
      { text: "The Purchaser will not use the car or allow anybody else to use the car for any unlawful act or terrorist activity." },
      { text: "That the purchaser will be fully and solely liable and responsible for the any claim, compensation, fines, which are the outcome of any accident or unlawful use of the vehicle or any act which is/or would amount to terrorist activity, from the date of sale/purchase and the seller will not be approached." },
      { text: "In case of any such claim, compensation, fine after the date of sale/purchase, the purchaser will be solely liable and responsible and will make good the losses at his own cost." },
      { text: "The purchaser will deliver the custody of the car to the court, in case the Court wants the car for inspection." },
      { text: "The purchaser will deliver the custody of the car to the seller, in case the seller wants the car for inspection, for production before court or if the vehicle is used or is suspected to/would be used in unlawful act or terrorist activity or if the seller is been or is likely to be implicated as a party to any suit or criminal complaint or any court proceeding/s." },
      { text: "The Seller will not be held liable and responsible for any mechanical defect which occurs after the date of sale/purchase, even if the defect so occurs is the result of any earlier defect." },
      { text: "The insurer M/s. __________________________ General Insurance Company (India) Ltd. is acting as a witness to this agreement between Seller and Purchaser, whereas the Purchaser has agreed to indemnify both the Seller and Insurer in the event of non-compliance or breach of any of the Points #4 to #11." },
      { text: "The Purchaser is ready and willing to purchase the said car in the condition as it is." },
      { text: "The seller will be getting the policy cancelled w.e.f. {{executionDate}}." },
      { text: "IN WITNESS WHERE OF the parties have put their respective hands the day and year first hereinabove written." },
      { text: "Deponents" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
      { text: "Mob: Mob:" },
      { text: "In Witness Of" },
      { text: "__________________________   __________________________" },
      { text: "Add:Add:" },
      { text: "Sign:Sign:" },
    ],
  },
  "corporate-guarantee": {
    id: "corporate-guarantee",
    baseType: "deed",
    name: "Corporate Guarantee",
    deedTitle: "CORPORATE GUARANTEE",
    roleA: "SELLER",
    roleB: "PURCHASER",
    description: "A supplier's unconditional guarantee against an advance paid on a purchase order, reducing as the goods are delivered.",
    body: [
      { text: "CORPORATE GUARANTEE", heading: true },
      { text: "1.This Corporate Guarantee executed on {{executionDate}} by (__________________________ AND __________________________ COMPANY) a firm incorporated in India and having its factory at __________________________ ) (Herein after called the SELLER which expression shall, unless repugnant to the context or contrary to the meaning thereof, includes its successors and assigns) in favour of M/s. __________________________ & POWER LIMITED, a Company registered under the Indian Companies Act, __________________________ and having its Registered Office at __________________________ ) __________________________ (Herein after called “THE PURCHASER” which expression shall, unless repugnant to the context or contrary to the meaning thereof includes its successors and assigns)" },
      { text: "2.The seller having received from the purchasers their purchase order No.: __________________________ Dated {{executionDate}} for the supply of Manufacture and supply of SQ __________________________ – 26 NOS for __________________________ 25 MW __________________________ and having accepted the said purchase order in all respects." },
      { text: "3.At the sellers request, the purchaser has agreed to pay 20% advance payment against submission of Corporate Guarantee to seller a sum of Rs. __________________________ /- (Rupees __________________________ only) being of advance of the purchase order against undertaking of the sellers." },
      { text: "4.The seller hereby furnish this unconditional and irrevocable undertaking in favour of the purchaser that in the event of seller failing to supply the ordered equipment and adjust the advance paid by the purchaser as above and the purchaser claiming any sum(s) towards refund of advance amount paid by the purchaser, the seller will remit such sums not exceeding Rs. __________________________ /- (Rupees __________________________ only) immediately on the purchaser’s first simple demand not withstanding that any dispute has arisen or any dispute which may arise at any stage." },
      { text: "5. This Corporate Guarantee shall remain valid up to {{executionDate}} or till the date of delivery duly and completely to the purchaser of the said equipment against the said order and adjustment of the entire amount of advance paid by the purchaser whichever is earlier" },
      { text: "6. With each effected supply, this Corporate Guarantee will be automatically reduced and adjusted proportionately to the extent of the invoice value of each supply, irrespective of whether the supply consists of a complete unit or part thereof." },
      { text: "7. Not withstanding any this stated here in above :" },
      { text: "Seller liability to the purchaser under this guarantee shall be limited to Rs. __________________________ /- (Rupees __________________________ only)." },
      { text: "The Corporate Guarantee Will remain valid up to {{executionDate}} regardless of the fact whether the original of this guarantee is returned to seller or not." },
      { text: "Unless a claim in writing under the Corporate Guarantee is received by the seller on or before {{executionDate}} all rights of the purchaser under this corporate Guarantee shall be forfeited and the seller shall be received and discharged from all their liabilities under this guarantee and the seller will not cancel the submitted cheque until completion of total advance adjusted." },
      { text: "In witness where of, the seller have here unto affixed their signature the day, month and year first above written." },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
    ],
  },
  "mod-title-deeds": {
    id: "mod-title-deeds",
    baseType: "deed",
    name: "Memorandum of Deposit of Title Deeds",
    deedTitle: "MEMORANDUM OF DEPOSIT OF TITLE DEEDS",
    roleA: "MORTGAGOR",
    roleB: "MORTGAGEE BANK",
    description: "Records an equitable mortgage: the borrower has handed the title deeds to the bank to secure a sanctioned loan.",
    body: [
      { text: "MEMORANDUM OF DEPOSIT OF TITLE DEEDS", heading: true },
      { text: "This Memorandum of Deposit of Title Deeds executed at Chennai on this 30th day of __________________________ by" },
      { text: "Mr. {{nameA}} aged ___ years, S/O {{parentA}} and __________________________ D/O __________________________ aged ___ years, both are residing at {{addressA}} (hereinafter called Mortgagor/Depositor which expression shall, unless it be repugnant to the context or meaning thereof, be deemed to include his/her/their respective heirs, legal representatives, successors and assigns etc for creation of Equitable Mortgage by way of Deposit of the Title Deeds)" },
      { text: "To and in favour of" },
      { text: "__________________________ BANK LTD., a banking company, incorporated and registered under the companies act, __________________________ having its Registered Office at __________________________ ) __________________________ – __________________________ and a Branch Office, inter alia, at First Floor, __________________________ No: __________________________ __________________________ Chennai-__________________________ (hereinafter referred to as the Bank/Mortgagee which expression shall, unless it be repugnant to the context or meaning thereof, be deemed to mean and include its successors and assigns etc)." },
      { text: "WHEREAS, the Mortgagor have/has been sanctioned a loan of Rs. __________________________ /-(Rupees __________________________ only) at Chennai by the Mortgagee/Bank." },
      { text: "WHEREAS, the Mortgagor has agreed that the repayment of the said loan of Rs. __________________________ /-(Rupees __________________________ only) shall be secured by an Equitable Mortgage by way Deposit of the Deeds of immovable property/ies belonging to him/her/them" },
      { text: "WHEREAS, the Mortgagor has irrevocably agreed to create the security interest in favour of the Mortgagee/Bank as the __________________________ in accordance with the provisions of Section-58(f) of Transfer of Property Act, __________________________" },
      { text: "WHEREAS, the Mortgagor is/are legally authorized to deposit the said Title Documents with an intent to create a mortgage on the said Immovable Property/ies." },
      { text: "NOW THIS MEMORANDUM OF DEPOSIT OF TITLE DEEDS __________________________ THAT", heading: true },
      { text: "In consideration of sum of Rs. __________________________ /-(Rupees __________________________ only) advanced/to be advanced/agreed to be advanced by __________________________ Bank Ltd the Mortgagee as loan to MR. __________________________ P & __________________________ the Mortgagor, as security for due repayment of the said loan of Rs. __________________________ /-(Rupees __________________________ only)) together with interest that may become due and payable, the Mortgagor has/have this day deposited with the Mortgagee/Bank the Title Deeds more fully described in Schedule A relating to the property mentioned Schedule D herein under mentioned with an intent to create an Equitable Mortgage by way of Deposit of Title Deeds of the said property owned by the Mortgagor, including interest, commitment charges, cost charges and other monies and may become due and payable from time to time by them to the Mortgagee/Bank." },
      { text: "SCHEDULE “ A”", heading: true },
      { text: "(List of the Original documents of title Deposited)", heading: true },
      { text: "1. Sale Deed, Document No __________________________ Dated __________________________ in favor of MR. __________________________ P & __________________________" },
      { text: "SCHEDULE B PROPERTY", heading: true },
      { text: "(Extent of the land covered in __________________________ )", heading: true },
      { text: "All that piece and parcel of land comprised and admeasuring an extent of __________________________ ( 3,53,637.__________________________ sq.ft i.e 8.12 acres) comprised in __________________________ (part), 119 (part), 120 (part), 134, 135, __________________________ (part), __________________________ (part) situated at __________________________ Village, __________________________ Taluk, Chennai District (Formerly within Tiruvallur District), __________________________ and situated within the Registration District of Chennai Central and Registration Sub-District of __________________________ : and bounded on the" },
      { text: "North by: Land in __________________________ : __________________________ 15.2 mtr Wide Road and12 mtr Wide Road" },
      { text: "South by: Lands in __________________________ : __________________________" },
      { text: "East by: 12 mtr Wide Road" },
      { text: "West by: Land in __________________________ : __________________________ 132 & 133." },
      { text: "and situated within the Registration District of Chennai Central and Registration Sub-District of __________________________" },
      { text: "SCHEDULE C PROPERTY", heading: true },
      { text: "(Extent of the land earmarked for Club House)", heading: true },
      { text: "All that piece and parcel of proportionate land towards cluster __________________________ admeasuring an extent of __________________________ (__________________________ sqft) out of the total extent of __________________________ (__________________________ sq.ft i.e 1.01 acres) comprised in __________________________ (part), 144(part) and __________________________ (part) situated at __________________________ Village, __________________________ Taluk, Chennai District (formerly within Tiruvallur District), Tamil Nadu," },
      { text: "and bounded on the" },
      { text: "North by : __________________________ Land in Survey No __________________________ and 12’ M wide Link Road," },
      { text: "South by : Land in Survey No __________________________ and __________________________" },
      { text: "East by : 12’ M wide Link Road," },
      { text: "West by : __________________________ land in Survey No __________________________ & __________________________" },
      { text: "and situated within the Registration District of Chennai Central and Registration Sub-District of __________________________" },
      { text: "THE SCHEDULE ‘D’", heading: true },
      { text: "PROPERTY TO BE __________________________", heading: true },
      { text: "All that piece and parcel of 2+S Bedroom Apartment bearing __________________________ -__________________________ on the Fourth Floor in the ‘R’ Block in Cluster-__________________________ /CELESTE of the residential complex known as “__________________________ ”, having a carpet area of __________________________ and private balcony area of __________________________ and proportionate common area of __________________________ (which is inclusive of common areas) totaling to a super built up area of __________________________ with the right to usage of 1 car parking space with UDS of land __________________________ land toward cluster-2 admeasuring an extent of __________________________ (__________________________) out of the total extent of __________________________ (__________________________ i.e 1.01 __________________________ ), comprised in Survey No __________________________ (part), 144(part) and __________________________ (part), situated at __________________________ Village, __________________________ Taluk, Tiruvallur District." },
      { text: "And situated within the Sub-Registration District of __________________________ and Registration District of North Chennai." },
      { text: "IN WITNESS WHEREOF, the Parties hereto have set their respective hands on these presents in the presence of the following Witnesses." },
      { text: "WITNESSES:", heading: true },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
    ],
  },
  "mod-title-deeds-bank": {
    id: "mod-title-deeds-bank",
    baseType: "deed",
    name: "Memorandum of Deposit of Title Deeds — Bank Form",
    deedTitle: "MEMORANDUM OF DEPOSIT OF TITLE DEEDS",
    roleA: "EXECUTANT",
    roleB: "BANK",
    description: "The longer bank form of the same memorandum, with the list of deeds deposited and the property schedule set out.",
    body: [
      { text: "MEMORANDUM OF DEPOSIT OF TITLE DEEDS", heading: true },
      { text: "This Memorandum of Deposit of Title Deeds, executed on this {{executionDate}} by Mr. {{nameA}} Son of {{parentA}},[Aadhar No. {{aadhaarA}}] [Pan No.__________________________ ] Hindu aged ___ years residing at {{addressA}} hereinafter referred to as the Executant] which term shall, wherever the context so admits and permits shall mean and include their heirs, executors and administrators, successors and assigns," },
      { text: "IN FAVOUR OF", heading: true },
      { text: "Indian Overseas Bank, a Body Corporate constituted under the Banking Companies [Acquisition and Transfer of Undertakings] Act, __________________________ having its Central Office at __________________________ hereinafter referred to as the Bank”] which term shall, wherever the context so admits and permits shall mean and include their heirs, executor and administrator, successor and assigns." },
      { text: "The Executant has already deposited on {{executionDate}} the following documents of title relating to his property listed hereunder with the Bank with intent to create an equitable mortgage in favour of the Bank over the property to which the documents relate to and described hereunder for the purpose of securing repayment to the Bank of all the amounts owing to the Bank under advances made and to be made to __________________________ Son of __________________________ by the Bank by way of Housing Loan of Rs. {{amount}}/- [Rupees __________________________ lakhs Only] together with interests, cost, charges and expenses thereon." },
      { text: "The executant further declare that the documents deposited are all that were in his possession and control and that the property is not charged or encumbered in any way whatsoever." },
      { text: "LIST OF DOCUMENTS OF TITLE DEEDS;", heading: true },
      { text: "1. Partition Deed dated {{executionDate}} between Mr,__________________________ & __________________________ both are sons of Mr,__________________________ registered as Document No __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "2. “A” register in favour of __________________________ & __________________________ [Xerox Copy]" },
      { text: "3.Sale Deed dated {{executionDate}} in favour of __________________________ Son of __________________________ [Minor] rep by his mother and guardian __________________________ executed __________________________ and others registered as Document No __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "4.Sale Deed dated {{executionDate}} in favour of __________________________ Wife of __________________________ executed __________________________ and others registered as Document No __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "5.Patta No.507 stands in the name of __________________________ Wife of __________________________ [Xerox Copy]" },
      { text: "6. __________________________ chitta, adangal, other revenue records stands in the name of __________________________ Wife of __________________________ [Xerox Copy]" },
      { text: "7.Sale deed dated {{executionDate}} in favour of __________________________ Son of __________________________ executed by __________________________ Son of late __________________________ registered as Document No __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "8.Sale deed dated {{executionDate}} in favour of __________________________ [Minor] Son of __________________________ executed by __________________________ Son of late __________________________ and others registered as Document No __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "9. Gift Deed dated {{executionDate}} in favour of The __________________________ executed by __________________________ Wife of __________________________ and __________________________ and __________________________ both are Sons of __________________________ registered as Document No __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "10. __________________________ permission of” LAKSHMI NAGAR” Lay out No.130 of __________________________ and proceeding letter No: __________________________ dated {{executionDate}} comprised in __________________________ 86 &94 in __________________________ Village, in favour of __________________________ Wife of __________________________ issued by Member Secretary, __________________________ [Xerox Copy]" },
      { text: "11. Deed of Will dated {{executionDate}} in favour of __________________________ Wife of __________________________ and her legal heirs executed by __________________________ Wife of __________________________ registered as Document No. __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "12. Deed of Settlement dated {{executionDate}} in favour of __________________________ Daughter of __________________________ rep by her mother and guardian __________________________ executed by __________________________ Son of __________________________ registered as Document No __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "13. Death & __________________________ of Late __________________________ Wife of __________________________ issued by Tahsildar, __________________________ [Xerox Copy]" },
      { text: "14. Patta No.39, __________________________ adangal, other revenue records stands in the name of __________________________ and __________________________ both are Sons of __________________________ [Xerox Copy]" },
      { text: "15. Deed of Settlement dated {{executionDate}} in favour of __________________________ Son of __________________________ executed by __________________________ Daughter of __________________________ registered as Document No __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "16.Deed of Settlement dated {{executionDate}} in favour of __________________________ Son of late __________________________ executed by __________________________ Son of Late __________________________ registered as Document No __________________________ of __________________________ at __________________________ [Xerox Copy]" },
      { text: "17. Death certificate of late __________________________ dated {{executionDate}} issued by Greater Chennai Corporation[Xerox Copy]" },
      { text: "18.__________________________ dated {{executionDate}} in favour of __________________________ Wife of Late __________________________ and others issued by Tahsildar, __________________________ [Xerox Copy]" },
      { text: "19. Partition Deed dated {{executionDate}} entered between __________________________ Wife of Late __________________________ 2.__________________________ Wife of __________________________ and Daughter of late __________________________ 3.__________________________ Daughter of late __________________________ 4.__________________________ Wife of late __________________________ 5.__________________________ Son of late __________________________ 6.__________________________ Wife of __________________________ and Daughter of late __________________________ registered as Document No __________________________ of __________________________ at __________________________ T,Nagar [Xerox Copy]" },
      { text: "20.Patta Nos.__________________________ and __________________________ bearing plot No __________________________ 41,42, and 43, other revenue records stands in the name of __________________________ Wife of late __________________________ issued by Tahsildar, __________________________ Taluk[Xerox Copy]" },
      { text: "21.__________________________ No: __________________________ No: __________________________ bearing Plot No __________________________ 41,42,43, dated {{executionDate}} issued by The Commissioner, __________________________ [Original Copy]" },
      { text: "22. Sale Deed dated {{executionDate}} in favour of 1.__________________________ Son of __________________________ 2.__________________________ Wife of __________________________ executed by __________________________ Wife of Late __________________________ registered as Document No __________________________ of __________________________ at __________________________ [Original Copy]" },
      { text: "23.Patta No: __________________________ in favour of 1.__________________________ Son of __________________________ 2.__________________________ Wife of __________________________ issued by Tahsildar, __________________________ Taluk[Original Copy]" },
      { text: "24.Building Plan Permit No: __________________________ vide letter No: __________________________ dated {{executionDate}} obtained by1.__________________________ Son of __________________________ 2.__________________________ Wife of __________________________ issued by Commissioner, __________________________ , __________________________ Village, __________________________ Taluk, Tiruvallur District.[Original Copy]" },
      { text: "25. Agreement of sale dated {{executionDate}} in favour of __________________________ Son of __________________________ executed by 1.__________________________ Son of __________________________ 2.__________________________ Wife of __________________________ measuring an extent of __________________________ feet of land and built-up area around __________________________ feet in ground and first floor, individual Duplex house, including car parking with compound wall. Bearing Plot No. __________________________ West and East, comprised in Survey No __________________________ 86 and 94, patta No: __________________________ as per patta New Sub-Division __________________________ No: __________________________ and as per sub-Division No: __________________________ approval planning permit No: __________________________ : __________________________ dated {{executionDate}}, name and style of “ LAKSHMI NAGAR“ layout approval No: __________________________ of __________________________ vide __________________________ : __________________________ of __________________________ issued by Commissioner, __________________________ , situated at __________________________ Village, __________________________ Taluk, Tiruvallur District.[Original Copy]" },
      { text: "26. Encumbrance Certificate from {{executionDate}} to {{executionDate}} and from {{executionDate}} to {{executionDate}} and from {{executionDate}} to {{executionDate}} it discloses Nil encumbrances [Xerox Copy]" },
      { text: "27. Encumbrance Certificate No: __________________________ of __________________________ dated {{executionDate}} from {{executionDate}} to {{executionDate}} for 36 years it discloses Nil encumbrances [Original Copy]" },
      { text: "Schedule of Property" },
      { text: "All that piece and parcel of land measuring an extent of __________________________ feet of land and built-up area around __________________________ feet in ground and first floor, individual Duplex house, including car parking with compound wall. Bearing Plot No. __________________________ West and Plot No __________________________ comprised in Survey No __________________________ 86 and 94, patta No: __________________________ as per patta New Sub-Division __________________________ No: __________________________ and as per sub-Division __________________________ name and style of “LAKSHMI NAGAR“ layout approval __________________________ D/__________________________ 130 of __________________________ vide __________________________ : __________________________ of __________________________ situated at __________________________ Village, __________________________ Taluk, Tiruvallur District, bounded on the" },
      { text: "Boundaries:" },
      { text: "North by: Plot No __________________________ 79,80," },
      { text: "South By: __________________________ feet wide Road," },
      { text: "East by: Plot No. __________________________ East PT and 41 West PT," },
      { text: "West by: Plot No. __________________________ East & 42 West." },
      { text: "East To West on the Northern side -__________________________ Feet and 5.2 Inches," },
      { text: "East To West on the Southern side -__________________________ Feet and 5.2 Inches," },
      { text: "North to South on the Eastern side -__________________________ Feet," },
      { text: "North to South on the Western side -__________________________ Feet," },
      { text: "Within the Registration District of South-Madras and Sub Registration District of __________________________" },
      { text: "In witness where of the Executant has signed their name on the day month and year above written." },
      { text: "Witnesses" },
      { text: "__________________________   __________________________" },
      { text: "[EXECUTANT]", heading: true },
      { text: "__________________________   __________________________" },
      { text: "__________________________ By :Mr. __________________________" },
      { text: "__________________________   __________________________" },
      { text: "__________________________   __________________________" },
    ],
  },
};

export const CONTRACT_TEMPLATE_IDS = Object.keys(CONTRACT_TEMPLATES) as ContractTemplateId[];
