import type { AgreementType } from "./types";

/**
 * The service provider agreement, held verbatim.
 *
 * A business-to-business services and franchise contract: a company engages a
 * provider to market and source within a territory, against a franchise fee.
 * It shares nothing with the lettings or the sales — no rent, no premises, no
 * transfer of ownership — and its thirteen clauses run to twelve pages with
 * three annexures, so it is kept paragraph for paragraph as the office signed
 * it rather than rebuilt from parts.
 *
 * Transcribed from the PDF the office supplied. Everything identifying the two
 * companies in that copy — their names, registered addresses, CIN, constituted
 * attorney and the fee — is a {{token}} the builder fills or a blank rule the
 * counter completes.
 */

export interface ContractBlock {
  text: string;
  heading?: boolean;
}

export const SERVICE_PROVIDER_BODY: ContractBlock[] = [
  { text: "SERVICE PROVIDER AGREEMENT IN CONNECTION WITH", heading: true },
  { text: "MARKETING, SOURCING AND ALLIED ACTIVITIES", heading: true },
  { text: "THIS AGREEMENT is made at {{executionPlace}} and entered into on this {{executionDate}}." },
  { text: "BY AND BETWEEN M/s. {{companyName}} a company incorporated under the provisions of the Companies Act, 1956, having its registered address at {{blank}} hereinafter referred to “THE COMPANY” (which expression shall unless it be repugnant to the context or contrary to the meaning hereof be deemed to mean and include his / /its legal heirs, executors , administrators ,successors in interest and her permitted assigns) of the", heading: true },
  { text: "ONE PART AND", heading: true },
  { text: "M/s. {{providerName}} a company incorporated under the provisions of the Companies Act, 1956, having its registered address at {{blank}} having CIN – {{blank}} represented by its duly Constituted Attorney {{blank}} (Hereinafter referred to as “SERVICE PROVIDER” which expression shall, unless it be repugnant to the context or meaning thereof, be deemed to mean and include its successors, Legal heirs, administrators, executors, successors and permitted assigns and referred to as the party of the OTHER PART. (Company and the Service Provider are collectively referred to herein as “PARTIES”)" },
  { text: "WITNESSES AS FOLLOWS:", heading: true },
  { text: "I. WHEREAS M/s. {{companyName}} is engaged in business of Logistic such as Procurement Logistics, Production Logistics, Sales Logistics, Inbound transportation, Outbound transportation, Fleet management, Warehousing, Order fulfilment, Inventory management etc. and have the necessary experience and expertise in that field;" },
  { text: "II. WHEREAS the M/s. {{providerName}} are in business of B2B ECommerce Business, Courier Services etc. and have the necessary experience and expertise in that field;" },
  { text: "III. WHEREAS the parties hereto have decided to focused and come together for their business such as transportation, distribution, and storage of goods etc to be known as “Logistic Project” (hereinafter referred to as the \"Project\");" },
  { text: "IV. WHEREAS M/s. {{companyName}} and M/s. {{providerName}} both having the necessary infrastructure and the capabilities of providing the services required for the project have agreed to do together business for the Project as mentioned above hence M/s. {{companyName}} and M/s. {{providerName}} are desirous of entering into a Service Provider Agreement in terms hereof;" },
  { text: "V. WHEREAS M/s. {{companyName}} and M/s. {{providerName}} are desirous of recording the Agreement with regard thereto and the agreement arrived at between them;" },
  { text: "VI. WHEREAS for the purpose of business convenience and with a view to effectively put into practice the products and Services listed in ANNEXURE herein in the places more particularly mentioned in ANNEXURE herein (hereinafter referred to “TERRITORY”) and more specifically as dealt with in these presents, the company is desirous of utilizing one or more Service Provider/s to present and market the products and Services to the customers. And Service Provider the remuneration / fees in the manner as stated in Annexure." },
  { text: "VII. WHEREAS the Service Provider named herein is the owner and operator of Logistics (“Platform”) and has represented and offered to the company that it has the necessary skill, experience," },
  { text: "expertise and infrastructure to act as the Service Provider to the company to source, market and to carry out the incidental / allied activities related thereto within the territory." },
  { text: "VIII. AND WHEREAS relying on the representation made by the Service Provider the Company has accepted the said offer and hereby engages the Service Provider to market the products and to source the business for the Company within the territory, on a non-exclusive basis and subject to the terms and conditions contained hereunder: -" },
  { text: "NOW THEREFORE THIS AGREEMENT WITNESSETH AND IT IS", heading: true },
  { text: "HEREBY AGREED BY AND BETWEEN THE PARTIES HERETO AS UNDER:" },
  { text: "1. CONSTRUCTION: -", heading: true },
  { text: "1.1 Unless the context otherwise requires, any reference to a statutory provision shall include such provision/s as from time to time modified or re-enacted or consolidated in so far as such modification, re-enactment or consolidation applies or is capable of applying to any transaction/s entered into herein" },
  { text: "1.2 References to clauses, recitals, schedules and annexure are to the clauses, recitals, schedules and annexure of this agreement." },
  { text: "1.3 The headings are for convenience only and shall not affect the interpretation thereof." },
  { text: "1.4 Unless the context otherwise requires, words importing the singular shall include the plural and vice versa." },
  { text: "1.5 Unless it is repugnant to the context, references to persons will be construed so as to include bodies’ corporate, unincorporated associations and partnerships." },
  { text: "1.6 References to any gender shall include the other genders." },
  { text: "1.7 Unless otherwise specified, all references to months are to calendar months." },
  { text: "1.8 Unless specified otherwise or repugnant to the context, references in this agreement to any party shall also refer to that party’s successors and permitted assignees." },
  { text: "2. TENURE:", heading: true },
  { text: "2.1 This agreement shall come into force on its execution and shall continue till such time until terminated in the manner as mentioned in this agreement. Any modification/changes/amendments to this agreement during its currency shall be effected/varied only in writing duly signed by both the parties herein." },
  { text: "3. DUTIES, RESPONSIBILITIES AND ALLIED COVENANTS OF/BY THE", heading: true },
  { text: "SERVICE PROVIDER:" },
  { text: "3.1 The Service Provider shall reach out to potential buyers on its Platform to generate qualified leads for the Company" },
  { text: "3.2 The Service Provider shall put forth all mechanisms in place to the best of his /its ability to increase the business volume. It shall represent the interest of the company through systematic canvassing, and Services to potential customers within the territory." },
  { text: "3.3 The Service Provider shall provide such assistance and support to the company during the Inbound transportation, Outbound transportation, Fleet management, Warehousing, Order fulfilment, Inventory management etc. or any such other promotional activities as and when required by the company." },
  { text: "3.4 It is one of the paramount duties of the Service Provider to ensure that the obligations under this agreement will be undertaken and performed by his / its staff/personnel/representatives who possess adequate qualifications, experience, competency and skill sets who shall comply with the Code and all obligations of the Service Provider contained in this agreement besides applying the good industry practice. Furthermore, neither the Service Provider nor its personnel / employees / representatives shall make any unauthorized statements, claims, warranties or representations concerning the bank / company or its products and Services. Also, neither the Service Provider nor its personnel / employee / representatives shall engage in any conduct (either in writing or verbally) that may be prejudicial to the interest, business, good will or reputation of the company including bank." },
  { text: "3.5 It is distinctly agreed upon and clearly understood by the Service Provider that it (the Service Provider) is not authorized to: a. Represent or hold itself out as a permanent and general agent or representative of the company, save and except what is expressly agreed by the company herein or to be communicated to the Service Provider in writing from time to time. b. Hold out any promises to applicants or guarantors of acceptance of their applications for any loan facility, product or Services by the company. c. Collect / levy any fees and /or other monies from applicants, except in cases where the Service Provider is specifically authorized by the company in writing to do so. d. Misuse the database created by it for the company by transferring or sharing the information with peer company’s/banks or to any third party / person or in any other manner or act which will be detrimental to the interest of the company." },
  { text: "3.6 The Service Provider shall not appoint any sub agent or otherwise transfer any of its rights and obligations under this agreement to" },
  { text: "any person / third party, without the explicit prior written consent of the company." },
  { text: "3.7 All money, cheques and other negotiable instruments, securities, policies and any other documents /particulars handled, delivered, collected or possessed by the Service Provider on behalf of any customer or the company shall be as that of a trustee for and on behalf of the customer or the company as the case may be." },
  { text: "3.8 The Service Provider shall allow the company reasonable opportunity during business hours to inspect any of the premises/offices located in India of the Service Provider to verify the quality of Service, stationery and point of sale advertising materials and other product related materials or terms/practices on the said premises subject to prior written notice and during normal business hours." },
  { text: "3.9 The Service Provider agrees to allow the Reserve Bank of India (RBI) or persons authorized by the company or RBI to access the documents, records of transactions and other necessary information given to, stored in or processed by the Service Provider within a reasonable time. In the event the same are not made accessible to RBI or the company within a reasonable time, the company reserves the right to recover from the Service Provider the supervisory fee, if any, to be paid to RBI by the company. The Service Provider hereby recognize the right of the company or the RBI to cause an inspection to be made on the Service Provider and its books and accounts by one or more of its officers or employees or other persons." },
  { text: "3.10 The Service Provider shall abide by the Model Code of conduct issued by Reserve Bank of India and/or any other Regulatory/Statutory bodies and its amendments from time to time as specified by the company to the Service Provider from time to time and also execute any documents as may be required in this regard and any breach of the code shall be an event of termination of this agreement apart from the right of the company to demand / claim adequate damages." },
  { text: "3.11 Such other duties, functions and operations as may be explicitly authorized in writing by the company from time to time as per applicable laws." },
  { text: "4. COMPANY’S RIGHT /DISCRETION:", heading: true },
  { text: "4.1 It is distinctly and succinctly agreed upon by the parties herein that the company is under no obligation to accept the customers sourced or proposed or recommended by the Service Provider and that the company may in its sole discretion and without assigning any reason refuse to consider or accept the customers sourced or proposed or recommended by the Service Provider." },
  { text: "4.2 It is further agreed that the both parties shall not make any Third-Party Agreement/s with other companies regarding the" },
  { text: "same / similar product in which they are doing the Logistic Project business and the said agreement shall be renewed after every Five (5) years if both the parties agreed to work together in future." },
  { text: "5. CONSIDERATION PAYABLE BY THE SERVICE PROVIDER TO THE", heading: true },
  { text: "COMPANY AND RIGHTS CONNECTED THEREWITH." },
  { text: "5.1 In consideration of the Services agreed to be rendered to the company by the Service Provider under this agreement, the company agrees to pay the Service Provider the remuneration / fees in the manner as stated in Annexure to this agreement which shall be final and binding on the Service Provider which shall be a Non-Refundable Amount." },
  { text: "5.2 The Service Provider is bound by the company’s terms and conditions in respect of selling of products along with his primary role as a sourcing/marketing agent of the products as specified in Annexure. In the event of non-compliance of the same by the Service Provider, in addition to its other rights, the company shall be at liberty (at its sole discretion) to alter/vary the terms of remuneration of the Service Provider." },
  { text: "5.3 The Company shall be giving Rs.23 per parcel Commission to the Service Provider from 1st – 15th Business Commission shall be paid on the next month 02nd of every month & 16th – 30th Commission shall be paid on 17th of every month." },
  { text: "6. PERSONNEL / EMPLOYEES / OTHER STAFF ENGAGED BY THE", heading: true },
  { text: "SERVICE PROVIDER:" },
  { text: "6.1 Subject to what has been stated in clause (3) above, the Service Provider shall maintain full details pertaining to such personnel employed / engaged by it and shall provide such details to the company as and when required by the company. It is specifically agreed by the parties herein that each party shall be solely responsible and liable in all respects for its employees / personnel/other staff including (but not limited to) any breach of violation of the terms contained in this agreement or for any acts or omission or commitments by them." },
  { text: "6.2 The company shall not at any point of time be liable or responsible for the salaries, remuneration, perquisites or other conditions or Services of the personnel/ employees/ other staff (whether full time or part time) engaged by the Service Provider." },
  { text: "6.3 Nothing in this agreement shall create or be deemed to create the relationship of master and servant between the company and the Service Provider or the personnel/employees/other staff of the Service Provider. It is expressly agreed between the parties that the company shall not be liable or responsible in any manner nor be liable to pay any monetary compensation in any eventuality including death, injury sustained or monetary loss suffered by" },
  { text: "the personnel / employees / other staff of the Service Provider. The Service Provider undertakes to ensure that its personnel / employees / other staff will have no claim whatsoever against the company and shall not raise any industrial dispute either directly or indirectly with the company in respect of any of their Service conditions or otherwise. The Service Provider shall be solely responsible for payment of remuneration and compliance with applicable labour enactments in respect of such personnel / employees / other staff engaged by it. In the event of any such adverse claim being made by any of such personnel / employees / other staff, the Service Provider shall be liable to indemnify and unconditionally agrees to indemnify the company." },
  { text: "7. INTELLECTUAL PROPERTY RIGHTS OF THE COMPANY:", heading: true },
  { text: "7.1 All intellectual property rights, including without limitation trademarks, trade name, Service marks, logo, copyrights, advertising copy, material, graphics, etc of the company will remain the sole property of the company. On a case-to-case basis, the company may, at its absolute discretion, permit the use of its name and logo on the business cards and other stationery materials used by the Service Provider. It is understood by the Service Provider that the usage of company’s name and logo shall be solely for the purpose/s contained and dealt with in this agreement and will be subject to prior written approval of the company on the terms to be stipulated by the company. Such usage of name and logo of the company shall not create any right, title or interest in respect of the name, logo or intellectual property in favour of the Service Provider." },
  { text: "7.2 The Service Provider shall not do or omit to do any act or thing which may in the opinion of the company bring the name of the company or their corporate logo / brand image into disrepute or which may damage, conflict with or is detrimental to the interests of the company." },
  { text: "8. TERMINATION AND ITS EFFECTS THEREOF: This agreement shall stand terminated (with immediate effect) on the happening of any one or more of the following: -", heading: true },
  { text: "1. The Service Provider becoming incapable of carrying out the terms of this agreement or its duties herein;" },
  { text: "2. The Service Provider committing a breach of any provisions of this agreement which is not remedied for a period of thirty (30) days from the date of the notice;" },
  { text: "3. The Service Provider goes into liquidation or is wound up or if a provisional liquidator or official liquidator or receiver is" },
  { text: "appointed to take possession of its undertaking, business or assets;" },
  { text: "4. In the opinion of the company the interest will be in jeopardy should the Services from the Service Provider are continued;" },
  { text: "5. Change in the management or ownership of the Service Provider. Notwithstanding the clauses 10 (8.1 to 8.5) as mentioned above, each Party is entitled to terminate this agreement without assigning any reason whatsoever by giving one-month prior written notice to the other Party." },
  { text: "9. EFFECTS OF TERMINATION: - Upon termination or expiration as dealt with in this agreement, the Service Provider shall:-", heading: true },
  { text: "1. Immediately cease to operate as Service Provider and not hold itself in any way as the Service Provider of the company and refrain from any action that would or may indicate any relationship between it and the company." },
  { text: "2. Return to the company forthwith all materials, documents, confidential information, statements and all other properties of the company." },
  { text: "3. It is distinctly understood by the parties herein that expiration or termination of this agreement shall be without prejudice to the accrued rights of the company." },
  { text: "10. JURISDICTION:", heading: true },
  { text: "10.1 Any disputes arising out of this agreement in any manner whatsoever shall be dealt with and confined to the laws prevailing in India and within the exclusive jurisdiction of the courts in Mumbai only." },
  { text: "11. INDEMNIFICATION:", heading: true },
  { text: "11.1 Each party (“Indemnifying Party”) agrees that it shall indemnify, defend and hold harmless the other party and its officers, directors, affiliated companies, agents, employees" },
  { text: "(“Indemnifying Party”) harmless against any and all liabilities, actions, losses, judgments, payments made in settlement, suits, proceedings, demands, damages, claims, costs and expenses including reasonable attorney’s fees from third parties resulting form: a) Failure by the Indemnifying Party to perform any of its obligation under this Agreement, in accordance with the provision of this Agreement; b) Wrongful termination of, or abandonment of work under this Agreement; c) Infringement of any third-party Intellectual Property Right; d) Any act, commission or omission, negligence, misrepresentation, fraud, forgery, misconduct or violation of any of the terms and condition of this Agreement by the Indemnifying Party or its Personnel; The Indemnifying Party shall co-operate with Indemnified Party in defending any claim(s) against Indemnified Party by any local, state or central authority with respect to any levies, taxes, duties, fines, and / or penalties etc. due and payable by the Indemnifying Party, and shall indemnify the Indemnified Party, fully and without limit, against the same. The Indemnifying Party recognizes that the indemnities provided under this Agreement shall be in addition to and in lieu of any other remedy available to Indemnified Party under the Agreement or by law." },
  { text: "12. LIMITATION OF LIABILITY:", heading: true },
  { text: "12.1 Neither Party shall be liable to the Other Party for any indirect, incidental, contingent, consequential, punitive, exemplary, special or similar damages, including but not limited to, loss of profits or loss of data, whether incurred as a result of negligence or otherwise, irrespective of whatever either party has been advised of the possibility of the incurrence by the other party of any such damages." },
  { text: "12.2 Neither Party shall be liable to the Other Party for any suit claims, proceeding, damages, liability, expenses or costs in the event of the company incurring or sustaining any loss or damages or prejudiced by violation of any applicable laws; breach of confidentiality obligation herein, infringement of intellectual property rights or willful misconduct, fraud, negligence or misrepresentation or on account of failure to comply with the industry standards while dealing / interacting with the leads generated by the Service Provider for the Company further to this Agreement. The liability of Company as per the clause 19 of this agreement initiate only on act post generation of leads." },
  { text: "12.3 Neither Party shall be responsible for any consequential, special, remote or consequential loss. And the Company shall not hold" },
  { text: "the Service Provide liable for any loss / damages sustained by the Company vide this Agreement." },
  { text: "13. NOTICE:", heading: true },
  { text: "13.1 Any notice by either party to the other party shall be in writing and delivered at the address of the other party given herein below:- Company: M/s. {{companyName}}, {{blank}}. Service Provider: M/s. {{providerName}}, {{blank}}. Either party shall intimate the other as to the change of address in writing and from the date of receipt of the said communication by the addressee; the new address would take effect." },
  { text: "IN WITNESS WHEREOF, the parties hereto have hereunto set and subscribed their respective hands and seals the day and year first hereinabove written.", heading: true },
  { text: "FOR THE COMPANY — M/s. {{companyName}}   Name: {{blank}}   Address: {{blank}}   Signature:", heading: true },
  { text: "FOR THE SERVICE PROVIDER — M/s. {{providerName}}   Name: {{blank}}   Address: {{blank}}   Signature:", heading: true },
  { text: "ANNEXURE – I — SERVICES: {{blank}}", heading: true },
  { text: "ANNEXURE – II – TERRITORY / LOCATION The Territory / Location in which the Service Provider shall be working which shall be given by the Company by having Mutual Conversation with the Service provider.", heading: true },
  { text: "ANNEXURE – III – REMUNERATION / FRANCHISEE FEES Franchisee Fees which is NonRefundable Amount + Banner. Total Franchisee Cost – Rs. {{amount}}/-", heading: true },
];

/** The instrument it is drafted under — neither a letting nor a sale. */
export const SERVICE_PROVIDER_BASE: AgreementType = "deed";
